server:
  port: 8081
spring:
  application:
    name: shophub
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: wsy2642@
  redis:
    host: 192.168.12.100
    port: 6379
    password: wsy2642
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: shophub-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.shophub.messaging.event
        spring.json.use.type.headers: false
  cache:
    type: caffeine
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.shophub.entity # 别名扫描包
logging:
  level:
    com.shophub: debug
shophub:
  cache:
    local-shop-ttl-minutes: 3
    local-shop-type-ttl-minutes: 10
  mq:
    cache-evict-max-retry: 3
